project_name: quay-credential-provider

version: 2

env:
  - GO111MODULE=on
  - CGO_ENABLED=1
  - COSIGN_YES=true

before:
  hooks:
    - go mod tidy

builds:
  - binary: quay-credential-provider-{{ .Os }}-{{ .Arch }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - s390x
      - ppc64le
    goarm:
      - "7"
    ldflags:
      - -s -w

sboms:
  - artifacts: binary
    documents:
      - "${artifact}.spdx.sbom.json"

archives:
  - formats: ['binary']
    name_template: "{{ .Binary }}"
    allow_different_binary_count: true

signs:
  # Keyless
  - id: quay-credential-provider-keyless
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    cmd: cosign
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
    artifacts: binary
    output: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "SNAPSHOT-{{ .ShortCommit }}"
