apiVersion: kubelet.config.k8s.io/v1
kind: CredentialProviderConfig
providers:
  - name: quay-credential-provider
    matchImages:
      - ""
    defaultCacheDuration: "12h"
    env:
      - name: CREDENTIAL_FILE
        value: /etc/quay-credential-provider/authfile.json
    apiVersion: credentialprovider.kubelet.k8s.io/v1
  # - name: ecr-credential-provider
  #   matchImages:
  #     - "*.dkr.ecr.*.amazonaws.com"
  #     - "*.dkr.ecr.*.amazonaws.com.cn"
  #     - "*.dkr.ecr-fips.*.amazonaws.com"
  #     - "*.dkr.ecr.us-iso-east-1.c2s.ic.gov"
  #     - "*.dkr.ecr.us-isob-east-1.sc2s.sgov.gov"
  #   defaultCacheDuration: "12h"
  #   apiVersion: credentialprovider.kubelet.k8s.io/v1